import { useState, useEffect, useRef } from 'react';
import { Printer, Download, X, DollarSign, ChevronLeft, Calendar } from 'lucide-react';
import { supabase } from '@/lib/supabase/client';
import type { PayrollRecord } from '@/types';
import { useApp } from '@/context/AppContext';

interface EmployeePayslipViewProps {
    userId: string;
    onBack: () => void;
}

const EmployeePayslipView = ({ userId, onBack }: EmployeePayslipViewProps) => {
    const { t, lang } = useApp();
    const [settings, setSettings] = useState<Record<string, string>>({});
    const [records, setRecords] = useState<PayrollRecord[]>([]);
    const [selectedRecord, setSelectedRecord] = useState<PayrollRecord | null>(null);
    const [loading, setLoading] = useState(false);
    const printRef = useRef<HTMLDivElement>(null);

    useEffect(() => {
        if (userId) fetchRecords();
        fetchSettings();
    }, [userId]);

    const fetchSettings = async () => {
        const { data } = await supabase.from('company_settings').select('*');
        if (data) {
            const s: Record<string, string> = {};
            data.forEach(item => { s[item.key] = item.value; });
            setSettings(s);
        }
    };

    const fetchRecords = async () => {
        setLoading(true);
        const { data } = await supabase.from('payroll_records')
            .select('*, profiles(first_name, last_name, employee_code, department, position, bank_name, bank_account)')
            .eq('user_id', userId)
            .in('status', ['confirmed', 'paid'])
            .order('year', { ascending: false })
            .order('month', { ascending: false });
        if (data) setRecords(data as PayrollRecord[]);
        setLoading(false);
    };

    const fmt = (n: number) => n.toLocaleString(lang === 'th' ? 'th-TH' : 'en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 });
    const monthNames = [t.jan, t.feb, t.mar, t.apr, t.may, t.jun, t.jul, t.aug, t.sep, t.oct, t.nov, t.dec];

    const handlePrint = () => {
        if (!printRef.current) return;
        const w = window.open('', '_blank');
        if (!w) return;
        w.document.write(`
            <html><head><title>Payslip</title>
            <style>
                body { font-family: 'Segoe UI', Tahoma, sans-serif; padding: 40px; color: #333; }
                .payslip { max-width: 700px; margin: 0 auto; border: 2px solid #333; padding: 30px; }
                .header { text-align: center; border-bottom: 2px solid #333; padding-bottom: 15px; margin-bottom: 20px; }
                .header h1 { margin: 0; font-size: 24px; }
                .header p { margin: 5px 0; color: #666; }
                .info-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 10px; margin-bottom: 20px; }
                .info-item label { font-size: 12px; color: #888; display: block; }
                .info-item span { font-weight: 600; }
                table { width: 100%; border-collapse: collapse; margin-top: 10px; }
                th, td { padding: 8px 12px; border: 1px solid #ddd; text-align: left; font-size: 14px; }
                th { background: #f5f5f5; font-weight: 600; }
                .text-right { text-align: right; }
                .total-row { background: #f0f9ff; font-weight: bold; }
                .net-row { background: #10b981; color: white; font-weight: bold; font-size: 16px; }
                .footer { margin-top: 30px; text-align: center; font-size: 12px; color: #999; }
                @media print { 
                    @page { size: A4 portrait; margin: 15mm; }
                    body { padding: 0; margin: 0; -webkit-print-color-adjust: exact; print-color-adjust: exact; font-size: 10px; } 
                    .no-print { display: none; } 
                    .payslip-container { page-break-inside: avoid; }
                    table, tr, td, th, tbody, thead, tfoot { page-break-inside: avoid !important; }
                }
            </style></head><body>
            <div style="width: 100%; max-width: 850px; margin: 0 auto; box-sizing: border-box; position: relative;">
                ${printRef.current.innerHTML}
                <div class="footer">${t.generatedByHrms || 'Generated by HRMS'}</div>
            </div>
            <script>window.print();</script>
            </body></html>
        `);
    };

    return (
        <div className="animate-fadeIn min-h-screen bg-slate-100 dark:bg-slate-950 flex justify-center pt-0 md:pt-4">
            <div className="w-full lg:max-w-7xl bg-white dark:bg-[#0f172a] md:rounded-[2.5rem] shadow-xl md:border border-slate-200 dark:border-slate-800 flex flex-col overflow-hidden">
                {/* Header */}
                <div className="px-5 py-6 flex items-center justify-between shrink-0 border-b border-slate-100 dark:border-slate-800">
                <button onClick={onBack} className="w-10 h-10 bg-white dark:bg-slate-800 rounded-2xl flex items-center justify-center shadow-sm hover:shadow-md transition active:scale-95 text-slate-600 dark:text-slate-300">
                    <ChevronLeft size={20} className="mr-0.5" />
                </button>
                <h2 className="text-xl font-bold text-slate-800 dark:text-white">{t.payslip || 'สลิปเงินเดือน'}</h2>
                <div className="w-10 h-10"></div> {/* Spacer for centering */}
            </div>

            {/* Content List */}
            <div className="flex-1 overflow-y-auto px-5 py-6 scrollbar-hide">
                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
                    {records.map(r => (
                    <div key={r.id} onClick={() => setSelectedRecord(r)} className="bg-white dark:bg-slate-800 rounded-[2rem] p-5 shadow-sm border border-slate-100 dark:border-slate-700/50 cursor-pointer active:scale-95 transition-all w-full flex items-center gap-4 hover:border-emerald-200 dark:hover:border-emerald-500/30">
                        <div className="w-16 h-16 rounded-[1.2rem] bg-emerald-50 dark:bg-emerald-500/10 text-emerald-500 flex flex-col items-center justify-center shrink-0 shadow-inner">
                            <span className="text-xs font-bold uppercase tracking-wider">{monthNames[r.month - 1]}</span>
                            <span className="text-lg font-black">{r.year}</span>
                        </div>
                        <div className="flex-1 min-w-0">
                            <p className="font-bold text-slate-800 dark:text-slate-200 truncate">{t.salary || 'เงินเดือนสำหรับ'} {monthNames[r.month - 1]}</p>
                            <p className="text-sm text-slate-500 dark:text-slate-400 font-medium">฿{fmt(r.net_pay)}</p>
                        </div>
                        <div className="shrink-0 bg-emerald-500 text-white px-3 py-1 rounded-full text-[11px] font-bold tracking-widest uppercase shadow-sm">
                            {r.status === 'confirmed' ? 'APPROVED' : 'PAID'}
                        </div>
                    </div>
                ))}
                </div>

                {records.length === 0 && (
                    <div className="bg-white dark:bg-slate-800 rounded-[2rem] p-10 text-center border border-slate-100 dark:border-slate-700/50 shadow-sm mt-8">
                        <div className="w-16 h-16 bg-slate-50 dark:bg-slate-700/50 rounded-full flex items-center justify-center mx-auto mb-4 border border-slate-100 dark:border-slate-700">
                            <DollarSign size={24} className="text-slate-400 dark:text-slate-500" strokeWidth={2.5} />
                        </div>
                        <p className="text-slate-500 dark:text-slate-400 font-bold tracking-wide">{loading ? t.loading : (t.noPayslipsHint || 'ยังไม่มีสลิปเงินเดือนให้แสดง')}</p>
                    </div>
                )}
            </div>

            {/* Payslip Modal View */}
            {selectedRecord && (
                <div className="fixed inset-0 z-[150] bg-black/70 flex items-center justify-center p-0 sm:p-4 backdrop-blur-sm overflow-y-auto">
                    <div className="bg-white text-gray-900 w-full sm:max-w-4xl h-full sm:h-auto sm:rounded-2xl overflow-hidden shadow-2xl flex flex-col">
                        <div className="flex justify-between items-center p-4 border-b shrink-0">
                            <h3 className="font-black text-lg px-2 text-slate-800">สลิปเงินเดือน / Pay Slip</h3>
                            <div className="flex gap-2">
                                <button onClick={handlePrint} className="px-4 py-2.5 bg-indigo-600 text-white rounded-xl text-sm font-bold flex items-center gap-2 hover:bg-indigo-500 shadow-md active:scale-95 transition">
                                    <Printer size={16} /> <span className="hidden sm:inline">Print</span>
                                </button>
                                <button onClick={() => setSelectedRecord(null)} className="p-2.5 rounded-xl bg-slate-100 text-slate-500 hover:bg-slate-200 transition active:scale-95">
                                    <X size={20} />
                                </button>
                            </div>
                        </div>
                        <div ref={printRef} className="p-4 sm:p-8 overflow-y-auto flex-1 custom-scrollbar bg-slate-50">
                            <div className="payslip-container bg-white p-5 sm:p-10 shadow-sm border border-slate-200" style={{ fontFamily: '"Sarabun", sans-serif', color: '#111', width: '100%', maxWidth: '850px', margin: '0 auto', fontSize: '12px', lineHeight: '1.4' }}>
                                {/* Header Section */}
                                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: '20px', flexWrap: 'wrap', gap: '15px' }}>
                                    {/* Company Info */}
                                    <div style={{ flex: '1 1 200px' }}>
                                        <h2 style={{ fontSize: '15px', fontWeight: 'bold', margin: '0 0 10px 0', color: '#000' }}>{settings?.company_name || 'Your Company Name'}</h2>
                                        <table style={{ fontSize: '11px', width: '100%' }}>
                                            <tbody>
                                                <tr>
                                                    <td style={{ paddingRight: '8px', color: '#000', lineHeight: '1.2', width: '90px' }}>ชื่อ-นามสกุล:<br /><span style={{ fontSize: '9px', color: '#666' }}>Emp. name</span></td>
                                                    <td style={{ fontWeight: 'bold', verticalAlign: 'top', paddingTop: '2px' }}>{selectedRecord.profiles?.first_name} {selectedRecord.profiles?.last_name || ''} ({selectedRecord.profiles?.employee_code || '-'})</td>
                                                </tr>
                                                <tr>
                                                    <td style={{ paddingRight: '10px', color: '#000', paddingTop: '8px', lineHeight: '1.2' }}>ตำแหน่ง:<br /><span style={{ fontSize: '9px', color: '#666' }}>Position</span></td>
                                                    <td style={{ fontWeight: 'bold', paddingTop: '10px', verticalAlign: 'top' }}>{selectedRecord.profiles?.position || '-'}</td>
                                                </tr>
                                            </tbody>
                                        </table>
                                    </div>

                                    {/* Document Title and Dates */}
                                    <div style={{ flex: '1 1 200px' }}>
                                        <table style={{ marginLeft: 'auto', textAlign: 'left', fontSize: '11px', width: '100%' }}>
                                            <tbody>
                                                <tr>
                                                    <td style={{ paddingRight: '10px', color: '#000', lineHeight: '1.2', width: '90px' }}>รอบเบิกจ่าย:<br /><span style={{ fontSize: '9px', color: '#666' }}>Payroll Period</span></td>
                                                    <td style={{ fontWeight: 'bold', verticalAlign: 'top', paddingTop: '2px' }}>01-{new Date(selectedRecord.year, selectedRecord.month, 0).getDate()} {monthNames[selectedRecord.month - 1]} {selectedRecord.year}</td>
                                                </tr>
                                                <tr>
                                                    <td style={{ paddingRight: '10px', color: '#000', paddingTop: '8px', lineHeight: '1.2' }}>วันที่ชำระ:<br /><span style={{ fontSize: '9px', color: '#666' }}>Payment Date</span></td>
                                                    <td style={{ fontWeight: 'bold', paddingTop: '10px', verticalAlign: 'top' }}>{new Date(selectedRecord.year, selectedRecord.month, 0).getDate()} {monthNames[selectedRecord.month - 1]} {selectedRecord.year}</td>
                                                </tr>
                                                <tr>
                                                    <td style={{ paddingRight: '10px', color: '#000', paddingTop: '8px', lineHeight: '1.2' }}>เลขที่บัญชี:<br /><span style={{ fontSize: '9px', color: '#666' }}>Bank Account</span></td>
                                                    <td style={{ fontWeight: 'bold', paddingTop: '10px', verticalAlign: 'top' }}>{selectedRecord.profiles?.bank_account || '-'}</td>
                                                </tr>
                                            </tbody>
                                        </table>
                                    </div>
                                </div>


                                {/* Details Table (FlowAccount Style) */}
                                <div style={{ overflowX: 'auto', border: '1px solid #000' }}>
                                    <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: '11px', minWidth: '600px' }}>
                                    <thead>
                                        <tr>
                                            <th style={{ border: '1px solid #000', padding: '6px', width: '33.33%', backgroundColor: '#fff', textAlign: 'center', fontWeight: 'normal' }}>รายได้<br /><span style={{ fontSize: '9px', color: '#666' }}>Earnings</span></th>
                                            <th style={{ border: '1px solid #000', padding: '6px', width: '33.33%', backgroundColor: '#fff', textAlign: 'center', fontWeight: 'normal' }}>รายการหัก<br /><span style={{ fontSize: '9px', color: '#666' }}>Deductions</span></th>
                                            <th style={{ border: '1px solid #000', padding: '6px', width: '33.33%', backgroundColor: '#fff', textAlign: 'center', fontWeight: 'bold' }}>ยอดสะสมปี {selectedRecord.year}<br /><span style={{ fontSize: '9px', color: '#666' }}>YTD</span></th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <tr>
                                            {/* Earnings Column */}
                                            <td style={{ border: '1px solid #000', verticalAlign: 'top', padding: '0', height: '160px' }}>
                                                <table style={{ width: '100%', borderCollapse: 'collapse', whiteSpace: 'nowrap' }}>
                                                    <tbody>
                                                        <tr>
                                                            <td style={{ padding: '6px 8px', lineHeight: '1.2' }}>เงินเดือน/ค่าจ้าง<br /><span style={{ fontSize: '8px', color: '#666' }}>Salary/Wage</span></td>
                                                            <td style={{ padding: '6px 8px', textAlign: 'right', verticalAlign: 'top', fontWeight: 'bold' }}>{fmt(selectedRecord.base_salary)}</td>
                                                        </tr>
                                                        <tr>
                                                            <td style={{ padding: '6px 8px', lineHeight: '1.2' }}>ค่าล่วงเวลา<br /><span style={{ fontSize: '8px', color: '#666' }}>Overtime</span></td>
                                                            <td style={{ padding: '6px 8px', textAlign: 'right', verticalAlign: 'top', fontWeight: 'bold' }}>{fmt(selectedRecord.ot_amount)}</td>
                                                        </tr>
                                                        <tr>
                                                            <td style={{ padding: '6px 8px', lineHeight: '1.2' }}>ค่านายหน้า<br /><span style={{ fontSize: '8px', color: '#666' }}>Commission</span></td>
                                                            <td style={{ padding: '6px 8px', textAlign: 'right', verticalAlign: 'top', fontWeight: 'bold' }}>0.00</td>
                                                        </tr>
                                                        <tr>
                                                            <td style={{ padding: '6px 8px', lineHeight: '1.2' }}>โบนัส/เงินเสริม<br /><span style={{ fontSize: '8px', color: '#666' }}>Bonus & Others</span></td>
                                                            <td style={{ padding: '6px 8px', textAlign: 'right', verticalAlign: 'top', fontWeight: 'bold' }}>{fmt(selectedRecord.other_additions || 0)}</td>
                                                        </tr>
                                                    </tbody>
                                                </table>
                                            </td>

                                            {/* Deductions Column */}
                                            <td style={{ border: '1px solid #000', verticalAlign: 'top', padding: '0', height: '160px' }}>
                                                <table style={{ width: '100%', borderCollapse: 'collapse', whiteSpace: 'nowrap' }}>
                                                    <tbody>
                                                        <tr>
                                                            <td style={{ padding: '6px 8px', lineHeight: '1.2' }}>ประกันสังคม<br /><span style={{ fontSize: '8px', color: '#666' }}>Social Security Fund</span></td>
                                                            <td style={{ padding: '6px 8px', textAlign: 'right', verticalAlign: 'top', fontWeight: 'bold' }}>{fmt(selectedRecord.social_security)}</td>
                                                        </tr>
                                                        <tr>
                                                            <td style={{ padding: '6px 8px', lineHeight: '1.2' }}>ภาษีหัก ณ ที่จ่าย<br /><span style={{ fontSize: '8px', color: '#666' }}>Withholding tax</span></td>
                                                            <td style={{ padding: '6px 8px', textAlign: 'right', verticalAlign: 'top', fontWeight: 'bold' }}>{fmt(selectedRecord.withholding_tax)}</td>
                                                        </tr>
                                                        <tr>
                                                            <td style={{ padding: '6px 8px', lineHeight: '1.2' }}>ขาด/ลา/มาสาย<br /><span style={{ fontSize: '8px', color: '#666' }}>Absent/Leave/Late</span></td>
                                                            <td style={{ padding: '6px 8px', textAlign: 'right', verticalAlign: 'top', fontWeight: 'bold' }}>{fmt(selectedRecord.absent_deduction + selectedRecord.late_deduction)}</td>
                                                        </tr>
                                                        <tr>
                                                            <td style={{ padding: '6px 8px', lineHeight: '1.2' }}>รายการหักอื่นๆ<br /><span style={{ fontSize: '8px', color: '#666' }}>Others</span></td>
                                                            <td style={{ padding: '6px 8px', textAlign: 'right', verticalAlign: 'top', fontWeight: 'bold' }}>{fmt(selectedRecord.other_deductions || 0)}</td>
                                                        </tr>
                                                    </tbody>
                                                </table>
                                            </td>

                                            {/* YTD / Summary Column */}
                                            <td style={{ border: '1px solid #000', verticalAlign: 'top', padding: '0', height: '160px' }}>
                                                <table style={{ width: '100%', borderCollapse: 'collapse', whiteSpace: 'nowrap' }}>
                                                    <tbody>
                                                        <tr>
                                                            <td style={{ padding: '6px 8px', lineHeight: '1.2' }}>เงินได้สะสม<br /><span style={{ fontSize: '8px', color: '#666' }}>YTD earnings</span></td>
                                                            <td style={{ padding: '6px 8px', textAlign: 'right', verticalAlign: 'top', fontWeight: 'bold' }}>{fmt((selectedRecord.base_salary + selectedRecord.ot_amount + (selectedRecord.other_additions || 0)) * selectedRecord.month)}</td>
                                                        </tr>
                                                        <tr>
                                                            <td style={{ padding: '6px 8px', lineHeight: '1.2' }}>ภาษี ภงด. สะสม<br /><span style={{ fontSize: '8px', color: '#666' }}>YTD Tax</span></td>
                                                            <td style={{ padding: '6px 8px', textAlign: 'right', verticalAlign: 'top', fontWeight: 'bold' }}>{fmt((selectedRecord.withholding_tax) * selectedRecord.month)}</td>
                                                        </tr>
                                                        <tr>
                                                            <td style={{ padding: '6px 8px', lineHeight: '1.2' }}>เงินประกันสังคมสะสม<br /><span style={{ fontSize: '8px', color: '#666' }}>YTD SSF</span></td>
                                                            <td style={{ padding: '6px 8px', textAlign: 'right', verticalAlign: 'top', fontWeight: 'bold' }}>{fmt((selectedRecord.social_security) * selectedRecord.month)}</td>
                                                        </tr>
                                                        {/* Separator inside YTD */}
                                                        <tr><td colSpan={2} style={{ borderBottom: '1px solid #000' }}></td></tr>
                                                        <tr>
                                                            <td style={{ padding: '6px 8px', lineHeight: '1.2', color: '#047857' }}><b>รวมเงินได้สุทธิ</b><br /><span style={{ fontSize: '8px', color: '#666' }}>Net pay</span></td>
                                                            <td style={{ padding: '6px 8px', textAlign: 'right', verticalAlign: 'top', fontWeight: 'bold', fontSize: '13px', color: '#047857' }}><b>{fmt(selectedRecord.net_pay)}</b></td>
                                                        </tr>
                                                    </tbody>
                                                </table>
                                            </td>
                                        </tr>
                                    </tbody>
                                </table>

                                <div style={{ marginTop: '20px', textAlign: 'center', fontSize: '8px', color: '#000', borderTop: '0.5px solid #000', paddingTop: '8px' }}>
                                    เอกสารฉบับนี้พิมพ์จากระบบอิเล็กทรอนิกส์ ไม่จำเป็นต้องมีลายเซ็นผู้มีอำนาจ
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            )}
            </div>
        </div>
    );
};

export default EmployeePayslipView;
