
import { useState, useEffect, useRef } from 'react';
import { Printer, Download, X, Building, DollarSign, Clock } from 'lucide-react';
import { supabase } from '@/lib/supabase/client';
import type { PayrollRecord } from '@/types';

interface PayslipPageProps {
    settings: Record<string, string>;
}

import { useApp } from '@/context/AppContext';

const PayslipPage = ({ settings }: PayslipPageProps) => {
    const { t, lang } = useApp();
    const [month, setMonth] = useState(new Date().getMonth() + 1);
    const [year, setYear] = useState(new Date().getFullYear());
    const [records, setRecords] = useState<PayrollRecord[]>([]);
    const [selectedRecord, setSelectedRecord] = useState<PayrollRecord | null>(null);
    const [loading, setLoading] = useState(false);
    const printRef = useRef<HTMLDivElement>(null);

    useEffect(() => { fetchRecords(); }, [month, year]);

    const fetchRecords = async () => {
        setLoading(true);
        const { data } = await supabase.from('payroll_records')
            .select('*, profiles(first_name, last_name, employee_code, department, position, bank_name, bank_account)')
            .eq('month', month).eq('year', year)
            .in('status', ['confirmed', 'paid'])
            .order('created_at');
        if (data) setRecords(data as PayrollRecord[]);
        setLoading(false);
    };

    const fmt = (n: number) => n.toLocaleString(lang === 'th' ? 'th-TH' : 'en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 });
    const monthNames = [t.jan, t.feb, t.mar, t.apr, t.may, t.jun, t.jul, t.aug, t.sep, t.oct, t.nov, t.dec];

    const handlePrint = () => {
        if (!printRef.current) return;
        const w = window.open('', '_blank');
        if (!w) return;
        w.document.write(`
            <html><head><title>Payslip</title>
            <style>
                body { font-family: 'Segoe UI', Tahoma, sans-serif; padding: 40px; color: #333; }
                .payslip { max-width: 700px; margin: 0 auto; border: 2px solid #333; padding: 30px; }
                .header { text-align: center; border-bottom: 2px solid #333; padding-bottom: 15px; margin-bottom: 20px; }
                .header h1 { margin: 0; font-size: 24px; }
                .header p { margin: 5px 0; color: #666; }
                .info-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 10px; margin-bottom: 20px; }
                .info-item label { font-size: 12px; color: #888; display: block; }
                .info-item span { font-weight: 600; }
                table { width: 100%; border-collapse: collapse; margin-top: 10px; }
                th, td { padding: 8px 12px; border: 1px solid #ddd; text-align: left; font-size: 14px; }
                th { background: #f5f5f5; font-weight: 600; }
                .text-right { text-align: right; }
                .total-row { background: #f0f9ff; font-weight: bold; }
                .net-row { background: #10b981; color: white; font-weight: bold; font-size: 16px; }
                .footer { margin-top: 30px; text-align: center; font-size: 12px; color: #999; }
                @media print { 
                    @page { size: A4 portrait; margin: 15mm; }
                    body { padding: 0; margin: 0; -webkit-print-color-adjust: exact; print-color-adjust: exact; font-size: 12px; } 
                    .no-print { display: none; } 
                    .payslip-container { page-break-inside: avoid; }
                    table, tr, td, th, tbody, thead, tfoot { page-break-inside: avoid !important; }
                }
            </style></head><body>
            <div style="width: 100%; max-width: 850px; margin: 0 auto; box-sizing: border-box; position: relative;">
                ${printRef.current.innerHTML}
                <div class="footer">${t.generatedByHrms || 'Generated by HRMS'}</div>
            </div>
            <script>window.print();</script>
            </body></html>
        `);
    };

    return (
        <div className="space-y-6 animate-fadeIn">
            <div className="flex flex-wrap items-center justify-between gap-4 bg-white p-4 rounded-2xl border border-slate-200 shadow-sm">
                <div className="flex items-center gap-4">
                    <div className="flex items-center gap-2">
                        <Building size={20} className="text-indigo-600" />
                        <select value={month} onChange={e => setMonth(Number(e.target.value))} className="bg-slate-50 border border-slate-200 rounded-xl px-4 py-2.5 text-slate-800 text-sm font-bold focus:border-indigo-500 outline-none transition-all">
                            {monthNames.map((m, i) => <option key={i} value={i + 1}>{m}</option>)}
                        </select>
                    </div>
                    <select value={year} onChange={e => setYear(Number(e.target.value))} className="bg-slate-50 border border-slate-200 rounded-xl px-4 py-2.5 text-slate-800 text-sm font-bold focus:border-indigo-500 outline-none transition-all">
                        {[2025, 2026, 2027].map(y => <option key={y} value={y}>{y}</option>)}
                    </select>
                    {loading && <span className="text-xs text-indigo-500 font-bold animate-pulse flex items-center gap-2"><Clock size={14} className="animate-spin" /> {t.loading}</span>}
                </div>
            </div>

            {/* Payslip List */}
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                {records.map(r => (
                    <div key={r.id} className="bg-white p-6 rounded-[2.5rem] border border-slate-100 shadow-sm hover:border-indigo-200 transition-all cursor-pointer group relative overflow-hidden" onClick={() => setSelectedRecord(r)}>
                        <div className="absolute top-0 right-0 p-4">
                            <span className={`px-2.5 py-1 rounded-lg text-[10px] font-black tracking-widest uppercase border ${r.status === 'paid' ? 'bg-blue-50 text-blue-600 border-blue-100' : 'bg-emerald-50 text-emerald-600 border-emerald-100'}`}>{r.status}</span>
                        </div>
                        
                        <div className="mb-6">
                            <div className="w-12 h-12 rounded-2xl bg-slate-50 flex items-center justify-center mb-3 group-hover:bg-indigo-50 transition-colors">
                                <Building size={24} className="text-slate-400 group-hover:text-indigo-500" />
                            </div>
                            <h4 className="text-base font-black text-slate-800 group-hover:text-indigo-600 transition-colors">{r.profiles?.first_name} {r.profiles?.last_name}</h4>
                            <p className="text-[11px] font-bold text-slate-400 uppercase tracking-wider">{r.profiles?.department} • {r.profiles?.position}</p>
                        </div>

                        <div className="flex justify-between items-end pt-4 border-t border-slate-50">
                            <div>
                                <p className="text-[10px] font-bold text-slate-400 uppercase tracking-widest mb-1">{t.salary}</p>
                                <p className="text-2xl font-black text-slate-800 group-hover:text-emerald-600 transition-colors">฿{fmt(r.net_pay)}</p>
                            </div>
                            <div className="w-10 h-10 rounded-full bg-indigo-50 text-indigo-600 flex items-center justify-center translate-x-2 opacity-0 group-hover:opacity-100 group-hover:translate-x-0 transition-all">
                                <Printer size={18} strokeWidth={2.5} />
                            </div>
                        </div>
                    </div>
                ))}
                {records.length === 0 && !loading && (
                    <div className="col-span-full flex flex-col items-center justify-center py-24 bg-white rounded-[3rem] border border-slate-100 shadow-sm text-slate-400">
                        <DollarSign size={64} strokeWidth={1} className="mb-4 opacity-10" />
                        <p className="font-bold tracking-tight">{t.noPayslipsHint}</p>
                    </div>
                )}
            </div>

            {/* Payslip Modal */}
            {selectedRecord && (
                <div className="fixed inset-0 z-[150] bg-slate-900/40 flex items-center justify-center p-4 backdrop-blur-md overflow-y-auto animate-fadeIn">
                    <div className="bg-white w-full max-w-3xl rounded-[2.5rem] overflow-hidden shadow-2xl border border-white animate-scaleIn">
                        <div className="flex justify-between items-center px-8 py-6 border-b border-slate-50">
                            <div>
                                <h3 className="font-black text-xl text-slate-800 tracking-tight">{t.payslipTitle}</h3>
                                <p className="text-xs font-bold text-slate-400 uppercase tracking-widest">Employee Copy</p>
                            </div>
                            <div className="flex gap-3">
                                <button onClick={handlePrint} className="px-6 py-2.5 bg-indigo-600 text-white rounded-xl text-sm font-bold flex items-center gap-2 hover:bg-indigo-500 transition-all shadow-lg shadow-indigo-100 active:scale-95">
                                    <Printer size={16} strokeWidth={2.5} /> {t.print}
                                </button>
                                <button onClick={() => setSelectedRecord(null)} className="p-2.5 rounded-xl bg-slate-100 text-slate-500 hover:bg-slate-200 transition-all active:scale-90">
                                    <X size={20} strokeWidth={2.5} />
                                </button>
                            </div>
                        </div>
                        <div className="p-8 max-h-[70vh] overflow-y-auto custom-scrollbar">
                            <div ref={printRef} className="bg-white">
                                <div className="payslip-container" style={{ fontFamily: '"Sarabun", sans-serif', color: '#333', maxWidth: '100%', margin: '0 auto', fontSize: '13px', lineHeight: '1.4' }}>
                                    {/* ... Internal Payslip Design ... */}
                                    <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: '30px' }}>
                                        <div style={{ flex: 1 }}>
                                            <h2 style={{ fontSize: '16px', fontWeight: 'bold', margin: '0 0 15px 0', color: '#000' }}>{settings.company_name || t.company}</h2>
                                            <table style={{ fontSize: '12px' }}>
                                                <tbody>
                                                    <tr>
                                                        <td style={{ paddingRight: '10px', color: '#000', lineHeight: '1.2' }}>ชื่อนามสกุล(รหัส):<br /><span style={{ fontSize: '9px', color: '#666' }}>Emp. name (Code)</span></td>
                                                        <td style={{ fontWeight: 'bold', verticalAlign: 'top', paddingTop: '2px' }}>{selectedRecord.profiles?.first_name} {selectedRecord.profiles?.last_name || ''} ({selectedRecord.profiles?.employee_code || '-'})</td>
                                                    </tr>
                                                    <tr>
                                                        <td style={{ paddingRight: '10px', color: '#000', paddingTop: '10px', lineHeight: '1.2' }}>ตำแหน่ง:<br /><span style={{ fontSize: '9px', color: '#666' }}>Position</span></td>
                                                        <td style={{ fontWeight: 'bold', paddingTop: '12px', verticalAlign: 'top' }}>{selectedRecord.profiles?.position || '-'}</td>
                                                    </tr>
                                                </tbody>
                                            </table>
                                        </div>
                                        <div style={{ flex: 1, textAlign: 'right' }}>
                                            <h1 style={{ fontSize: '22px', fontWeight: 'bold', margin: '0 0 15px 0', color: '#000' }}>สลิปเงินเดือน / Pay Slip</h1>
                                            <table style={{ marginLeft: 'auto', textAlign: 'left', fontSize: '12px' }}>
                                                <tbody>
                                                    <tr>
                                                        <td style={{ paddingRight: '20px', color: '#000', lineHeight: '1.2' }}>รอบเงินเดือน:<br /><span style={{ fontSize: '9px', color: '#666' }}>Payroll Period</span></td>
                                                        <td style={{ fontWeight: 'bold', verticalAlign: 'top', paddingTop: '2px' }}>01-{new Date(selectedRecord.year, selectedRecord.month, 0).getDate()} {monthNames[selectedRecord.month - 1]} {selectedRecord.year}</td>
                                                    </tr>
                                                    <tr>
                                                        <td style={{ paddingRight: '20px', color: '#000', paddingTop: '10px', lineHeight: '1.2' }}>วันที่ชำระ:<br /><span style={{ fontSize: '9px', color: '#666' }}>Payment Date</span></td>
                                                        <td style={{ fontWeight: 'bold', paddingTop: '12px', verticalAlign: 'top' }}>{new Date(selectedRecord.year, selectedRecord.month, 0).getDate()} {monthNames[selectedRecord.month - 1]} {selectedRecord.year}</td>
                                                    </tr>
                                                    <tr>
                                                        <td style={{ paddingRight: '20px', color: '#000', paddingTop: '10px', lineHeight: '1.2' }}>เลขที่บัญชี:<br /><span style={{ fontSize: '9px', color: '#666' }}>Bank Account</span></td>
                                                        <td style={{ fontWeight: 'bold', paddingTop: '12px', verticalAlign: 'top' }}>{selectedRecord.profiles?.bank_account || '-'}</td>
                                                    </tr>
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                    <table style={{ width: '100%', borderCollapse: 'collapse', border: '1px solid #000', fontSize: '12px' }}>
                                        <thead>
                                            <tr>
                                                <th style={{ border: '1px solid #000', padding: '8px', width: '33.33%', backgroundColor: '#fff', textAlign: 'center', fontWeight: 'normal' }}>เงินได้<br /><span style={{ fontSize: '10px', color: '#666' }}>Earnings</span></th>
                                                <th style={{ border: '1px solid #000', padding: '8px', width: '33.33%', backgroundColor: '#fff', textAlign: 'center', fontWeight: 'normal' }}>รายการหัก<br /><span style={{ fontSize: '10px', color: '#666' }}>Deductions</span></th>
                                                <th style={{ border: '1px solid #000', padding: '8px', width: '33.33%', backgroundColor: '#fff', textAlign: 'center', fontWeight: 'normal' }}>ปี<br /><span style={{ fontSize: '10px', color: '#666' }}>{selectedRecord.year}</span></th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr>
                                                <td style={{ border: '1px solid #000', verticalAlign: 'top', padding: '0', height: '110px' }}>
                                                    <table style={{ width: '100%', borderCollapse: 'collapse' }}>
                                                        <tbody>
                                                            <tr>
                                                                <td style={{ padding: '4px 6px', lineHeight: '1.2' }}>เงินเดือน/ค่าจ้าง<br /><span style={{ fontSize: '9px', color: '#666' }}>Salary/Wage</span></td>
                                                                <td style={{ padding: '4px 6px', textAlign: 'right', verticalAlign: 'top', fontWeight: 'bold' }}>{fmt(selectedRecord.base_salary)}</td>
                                                            </tr>
                                                            <tr>
                                                                <td style={{ padding: '6px 8px', lineHeight: '1.2' }}>ค่าล่วงเวลา<br /><span style={{ fontSize: '9px', color: '#666' }}>Overtime</span></td>
                                                                <td style={{ padding: '6px 8px', textAlign: 'right', verticalAlign: 'top', fontWeight: 'bold' }}>{fmt(selectedRecord.ot_amount)}</td>
                                                            </tr>
                                                            <tr>
                                                                <td style={{ padding: '6px 8px', lineHeight: '1.2' }}>เงินได้อื่นๆ<br /><span style={{ fontSize: '9px', color: '#666' }}>Others</span></td>
                                                                <td style={{ padding: '6px 8px', textAlign: 'right', verticalAlign: 'top', fontWeight: 'bold' }}>0.00</td>
                                                            </tr>
                                                        </tbody>
                                                    </table>
                                                </td>
                                                <td style={{ border: '1px solid #000', verticalAlign: 'top', padding: '0', height: '160px' }}>
                                                    <table style={{ width: '100%', borderCollapse: 'collapse' }}>
                                                        <tbody>
                                                            <tr>
                                                                <td style={{ padding: '6px 8px', lineHeight: '1.2' }}>ประกันสังคม<br /><span style={{ fontSize: '9px', color: '#666' }}>Social Security Fund</span></td>
                                                                <td style={{ padding: '6px 8px', textAlign: 'right', verticalAlign: 'top', fontWeight: 'bold' }}>{fmt(selectedRecord.social_security)}</td>
                                                            </tr>
                                                            <tr>
                                                                <td style={{ padding: '6px 8px', lineHeight: '1.2' }}>ภาษีหัก ณ ที่จ่าย<br /><span style={{ fontSize: '9px', color: '#666' }}>Withholding tax</span></td>
                                                                <td style={{ padding: '6px 8px', textAlign: 'right', verticalAlign: 'top', fontWeight: 'bold' }}>{fmt(selectedRecord.withholding_tax)}</td>
                                                            </tr>
                                                            <tr>
                                                                <td style={{ padding: '6px 8px', lineHeight: '1.2' }}>ขาด/ลา/มาสาย<br /><span style={{ fontSize: '9px', color: '#666' }}>Absent/Leave/Late</span></td>
                                                                <td style={{ padding: '6px 8px', textAlign: 'right', verticalAlign: 'top', fontWeight: 'bold' }}>{fmt(selectedRecord.absent_deduction + selectedRecord.late_deduction)}</td>
                                                            </tr>
                                                        </tbody>
                                                    </table>
                                                </td>
                                                <td style={{ border: '1px solid #000', verticalAlign: 'top', padding: '0', height: '160px' }}>
                                                    <table style={{ width: '100%', borderCollapse: 'collapse' }}>
                                                        <tbody>
                                                            <tr>
                                                                <td style={{ padding: '6px 8px', lineHeight: '1.2' }}>เงินได้สะสม<br /><span style={{ fontSize: '9px', color: '#666' }}>YTD earnings</span></td>
                                                                <td style={{ padding: '6px 8px', textAlign: 'right', verticalAlign: 'top', fontWeight: 'bold' }}>{fmt((selectedRecord.base_salary + selectedRecord.ot_amount) * selectedRecord.month)}</td>
                                                            </tr>
                                                            <tr><td colSpan={2} style={{ borderBottom: '1px solid #000' }}></td></tr>
                                                            <tr>
                                                                <td style={{ padding: '6px 8px', lineHeight: '1.2' }}>รวมเงินได้<br /><span style={{ fontSize: '9px', color: '#666' }}>Total earnings</span></td>
                                                                <td style={{ padding: '6px 8px', textAlign: 'right', verticalAlign: 'top', fontWeight: 'bold' }}>{fmt(selectedRecord.base_salary + selectedRecord.ot_amount)}</td>
                                                            </tr>
                                                            <tr>
                                                                <td style={{ padding: '6px 8px', lineHeight: '1.2' }}>รวมรายการหัก<br /><span style={{ fontSize: '9px', color: '#666' }}>Total deductions</span></td>
                                                                <td style={{ padding: '6px 8px', textAlign: 'right', verticalAlign: 'top', fontWeight: 'bold' }}>{fmt(selectedRecord.social_security + selectedRecord.withholding_tax + selectedRecord.absent_deduction + selectedRecord.late_deduction)}</td>
                                                            </tr>
                                                            <tr>
                                                                <td style={{ padding: '6px 8px', lineHeight: '1.2' }}>เงินได้สุทธิ<br /><span style={{ fontSize: '9px', color: '#666' }}>Net pay</span></td>
                                                                <td style={{ padding: '6px 8px', textAlign: 'right', verticalAlign: 'top', fontWeight: 'bold', fontSize: '14px' }}>{fmt(selectedRecord.net_pay)}</td>
                                                            </tr>
                                                        </tbody>
                                                    </table>
                                                </td>
                                            </tr>
                                        </tbody>
                                    </table>
                                    <div style={{ display: 'flex', justifyContent: 'space-between', marginTop: '10px' }}>
                                        <div style={{ flex: 1, paddingRight: '20px' }}><p style={{ margin: '0 0 5px 0', fontSize: '11px', color: '#000' }}>หมายเหตุ:<br /><span style={{ fontSize: '9px', color: '#666' }}>Remarks</span></p></div>
                                        <div style={{ width: '200px', textAlign: 'center' }}>
                                            <p style={{ margin: '0 0 5px 0', fontSize: '11px', color: '#000', textAlign: 'left' }}>ลายเซ็นผู้จ่ายเงิน:<br /><span style={{ fontSize: '9px', color: '#666' }}>Employer's Signature</span></p>
                                            <div style={{ borderBottom: '1px solid #000', height: '20px', marginTop: '10px' }}></div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            )}
        </div>
    );
};

export default PayslipPage;
